### ISSUE TITLE
Issues with M2_HOME on Windows

### ISSUE THREAD

**Issue by mosabua** [takari/maven-wrapper#10]
Seems like people are having problems with M2_HOME settings in Windows. E.g. see https://github.com/rimerosolutions/maven-wrapper-example/issues/3#issuecomment-24521843

**Comment by orionll** [comment]
+1. I can't build my project with mvnw:

```
Error: M2_HOME is set to an invalid directory.
M2_HOME = "C:\Users\<...>"
Please set the M2_HOME variable in your environment to match the
location of the Maven installation
```

**Comment by sshikov** [comment]
+1. The same issue.

**Comment by mosabua** [comment]
This is fixed in the latest release from all I know.

**Comment by jkutner** [comment]
Confirmed this is fixed. If you are still running into it, you may need to update both your local version of `io.takari:maven:wrapper` and rerun the init command:

```
$ rm -rf ~/.m2/repository/io/takari/
$ mvn -N io.takari:maven:wrapper
```

I recommend closing this issue.

**Comment by mosabua** [comment]
Thanks for checking  @jkutner
