### ISSUE TITLE
Add instructions for .gitignore

### ISSUE THREAD

**Issue by onacit** [takari/maven-wrapper#102]
Maybe related to #50.
[gitignore.io](https://www.gitignore.io/api/maven) generates following for `maven`.

```

# Created by https://www.gitignore.io/api/maven
# Edit at https://www.gitignore.io/?templates=maven

### Maven ###
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties
.mvn/wrapper/maven-wrapper.jar

# End of https://www.gitignore.io/api/maven
```

It will be much better if some instructions related to `.gitignore`.

Say, something like this?

```
!.mvn/wrapper/maven-wrapper.jar
!.mvn/wrapper/maven-wrapper.properties
```

**Comment by sepe81** [comment]
This is not necessary anymore because of https://github.com/takari/maven-wrapper/pull/60

**Comment by onacit** [comment]
@sepe81 Indeed.

**Comment by mosabua** [comment]
Yes and no .. it is really a choice of the repository owner if they are ok with having a small binary jar in the source code repo or not. There is no hard and fast rule and as such we cant really make a guideline beyond that.
