### ISSUE TITLE
./mvnw line 214 missing ']' error due to spacing

### ISSUE THREAD

**Issue by hazendaz** [takari/maven-wrapper#109]
On line 214, in latest release, there is a bug.

if [ "$MVNW_REPOURL" = true]; then

It's missing the required space between 'true' and ']'.  

Can you fix that and releae a patch?

**Comment by mosabua** [comment]
new release now available

**Comment by hazendaz** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
