### ISSUE TITLE
The Maven Wrapper version 0.4.2 has been successfully setup for your project.

### ISSUE THREAD

**Issue by jnorthrup** [takari/maven-wrapper#114]
![image](https://user-images.githubusercontent.com/73514/54175885-1c8dad00-44bf-11e9-9337-32628aa839fd.png)

...

![image](https://user-images.githubusercontent.com/73514/54175909-30391380-44bf-11e9-94ab-4f993c89bf55.png)

nobody likes old pre 3.6 maven dude, what gives?

**Comment by mosabua** [comment]
You are using completely invalid syntax. Do not specify the wrapper version. Please check out the docs for actual correct usage.

https://github.com/takari/maven-wrapper/

The default Maven version used is 3.6.0 fyi.

**Comment by jnorthrup** [comment]
i run ubuntu.  ubuntu ant, maven, tomcat, etc.   installs are plainly stupid solutions to getting the desired tools.

i used a copy of mvnw from a diffferent project to run 

`../otherproject/mvnw -N io.takari:maven:wrapper`

when i run *mvn*  -N io.takari:maven:wrapper i see the string 

"The Maven Wrapper version 0.4.2 has been successfully setup for your project."

**Comment by sepe81** [comment]
@mosabua Maybe the problem only exists for projects with an existing maven wrapper. I tried to update maven wrapper with `mvn -N io.takari:maven:wrapper` but got the same "old" version as @jnorthrup .

Then I used `mvn -N io.takari:maven:0.7.4:wrapper` as proposed under https://github.com/takari/maven-wrapper/#developing-and-releasing (for development) and it worked for the latest version.

My environment: Git BASH for Windows

**Comment by mosabua** [comment]
The version used by the wrapper mojo will be depending on your local repo config and proxy config. It should look for latest and use that. Specifying the version as suggested by @sepe81 can force the usage of that version and is a reasonable workaround. Let me add that to the docs.
