### ISSUE TITLE
MavenWrapperDownloader includes extra space in default download url

### ISSUE THREAD

**Issue by plnordquist-pnnl** [takari/maven-wrapper#118]
I'm not sure how my maven wrapper was unable to load the maven-wrapper.properties file but it ended up using the DEFAULT_DOWNLOAD_URL constant in the MavenWrapperDownloader class and that constant has an extra space between the version and the '.jar'.  I ended up with the following line in my log:

`- Downloading from: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.4/maven-wrapper-0.5.4 .jar`

It also logged the failure with this exception `java.io.IOException: Server returned HTTP response code: 400 for URL: https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.4/maven-wrapper-0.5.4 .jar`

**Comment by mosabua** [comment]
Fixed. Will cut a new release after Maven 3.61. is released probably.

**Comment by mosabua** [comment]
https://github.com/takari/maven-wrapper/commit/ffd91ecafc491e5c7627f838cb3417a9c48bb665
