### ISSUE TITLE
Launch From Finder Does Not Work

### ISSUE THREAD

**Issue by jamesward** [takari/maven-wrapper#12]
If I try to run `mvnw` from Finder (Ctrl-Click; Open) it throws this error:

```
/Volumes/Home/j.ward/Desktop/hello-springboot/mvnw ; exit;
~ $ /Volumes/Home/j.ward/Desktop/hello-springboot/mvnw ; exit;
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
logout
```

This is probably because there is some special sauce need to change the cwd to the directory Finder is in, instead of the default (user home dir).

**Comment by mosabua** [comment]
While this might be nice, no one has cared enough to even look into it for a few years, so I am going to close this issue.
