### ISSUE TITLE
mvnw claims incorrectly to be a Maven 2 wrapper

### ISSUE THREAD

**Issue by TheUltimateDeployer** [takari/maven-wrapper#121]
It is a cosmetic error but it raises doubts about the functionality:

# Maven2 Start Up Batch script

The documentation explicitly states that Maven2 isn't supported.

**Comment by TheUltimateDeployer** [comment]
Fixed with PR #122

**Comment by mosabua** [comment]
Well... the current Maven 3 is an improved but compatible version of Maven 2 ... which was a new implementation of ideas from Maven 1 .. to which it was NOT compatible... so technically the Maven 2 reference is correct .. but also requires a lot of historic knowledge and by now Maven is basically Maven 3..  so I will bite and take this.
