### ISSUE TITLE
mvnw file contains trailing whitespace

### ISSUE THREAD

**Issue by ppalaga** [takari/maven-wrapper#123]
There is some trailing whitespace on line 249 of the mvnw file https://github.com/takari/maven-wrapper/blob/master/mvnw#L249

This is a problem for projects that use style checks/linters that do not allow trailing whitespace.

It is easy to fix, but actually, there is a lot of trailing whitespace in many other files of the current project. If you are interested @mosabua I could introduce editorconfig-maven-plugin [1] to catch all these things during the build so that it does not happen again. An advantage of the plugin is, that it can fix all violations it finds.

[1] https://github.com/ec4j/editorconfig-maven-plugin#editorconfig-maven-plugin

**Comment by ppalaga** [comment]
I have sent the PR https://github.com/takari/maven-wrapper/pull/124 in case you find the editorconfig idea good. BTW, the PR would also fix #120 .

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
