### ISSUE TITLE
Any easy way to create a maven wrapper from scratch, without mvn installed?

### ISSUE THREAD

**Issue by Eskibear** [takari/maven-wrapper#127]
> The easiest way to setup the Maven Wrapper for your project is to use the Takari Maven Plugin with its provided wrapper goal. 

Well, but it requires me to have mvn binary already installed on my machine.  My case is, I don't want to download the maven distribution, unzip it and set a bunch of environment variables. Is it possible to fetch a "global" mvnw, e.g. put under the userprofile folder, to replace mvn?

**Comment by mosabua** [comment]
Thats beyond the use case for the wrapper. If you need that .. just get Maven installed via a script or package manager or whatever. The wrapper is not meant to replace such tools.
