### ISSUE TITLE
Inconsistent use of MAVEN_CONFIG

### ISSUE THREAD

**Issue by sverhagen** [takari/maven-wrapper#128]
I am confused about `MAVEN_CONFIG`:

(For reference, I'm using the `maven:3.6-jdk-11` Docker image.)

In `/usr/share/maven/bin/mvn` any `MAVEN_CONFIG` environment variable is used as follows, added to a new `MAVEN_CMD_LINE_ARGS` variable, then seemingly not used for anything immediately:

    MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG $@"
    export MAVEN_CMD_LINE_ARGS

Whereas in a `mvnw` that I just created for Maven 3.6.1 there is the following, which is that the `MAVEN_CONFIG` value gets added to the command-line:

    exec "$JAVACMD" \
      $MAVEN_OPTS \
      -classpath "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar" \
      "-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
      ${WRAPPER_LAUNCHER} $MAVEN_CONFIG "$@"

For some reason, Bitbucket Pipelines sets `MAVEN_CONFIG=/root/.m2`; completely harmless when I run a build using `mvn`; breaking the build when using `./mvnw`:

    [ERROR] Unknown lifecycle phase "/root/.m2"

This seems like a bug, or at least an incompatibility between vanilla Maven and `mvnw`.

I cannot find documentation of what `MAVEN_CONFIG` is even supposed to do. (There is some use for it in [the Docker image](https://docs.docker.com/samples/library/maven/), which states that `/root/.m2` is the default for that environment variable; and they will unset it if you use [the right entrypoint](https://github.com/carlossg/docker-maven/commit/0490eff01e529b2d94789511b008d01a7b314953), but I think this is just a "different variable with the same name", and this is besides the point that `mvn` and `mvnw` behave differently.)

I think [this issue](https://issues.jenkins-ci.org/browse/JENKINS-47890) is acknowledging the same problem.

**Comment by gzm55** [comment]
#76 should fix this problem

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
