### ISSUE TITLE
please consider adding version string in first several lines of your mvnw and mvnw.cmd 

### ISSUE THREAD

**Issue by XenoAmess** [takari/maven-wrapper#129]
that make us be able to  know if we shall update it easier.

**Comment by mosabua** [comment]
I have no idea what you are asking

**Comment by XenoAmess** [comment]
for example add a line `#version 0.5.6-SNAPSHOT` at the beginning of mvnw.

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
