### ISSUE TITLE
Can I use exist settingsXML? 我能使用已有的settings.xml吗？

### ISSUE THREAD

**Issue by ElanZh** [takari/maven-wrapper#130]
I had a maven settings.xml already，
我已经有了一个settings的配置文件，
it include my own nexus server，and other setting like plugin,profile,
包含了自建的nexus私有仓，以及像插件和profile，
How can I use mvnw with this setting file for the default？
我如何在mvnw中默认就使用这个配置文件？

**Comment by Runrioter** [comment]
This issue is not about maven-wrapper. Do you want a settings.xml which is not located in `~/.m2/settings.xml` ?

**Comment by ElanZh** [comment]
Yeah,I mean it.
I want use another xml file.

**Comment by fbricon** [comment]
One way to do that is to bundle a Maven distro with your custom settings.xml, put it on a web server, and make the Maven wrapper in your projects point to that custom distro

**Comment by Runrioter** [comment]
@ElanZh  `./mvnw --settings <new setting file path>`

At the same time, you should have a pom.xml with a right repository configuration.

**Comment by ElanZh** [comment]
> 
> 
> @ElanZh `./mvnw --settings <new setting file path>`
> 
> At the same time, you should have a pom.xml with a right repository configuration.

It means I`d add ```--settings``` param everytime when I use  mvnw ?
意思是我需要每次执行 mvnw 时都要加 ```--settings``` 参数？

**Comment by Runrioter** [comment]
Yes. Why do you not change the default setting.xml file ?

**Comment by ElanZh** [comment]
> 
> 
> Yes. Why do you not change the default setting.xml file ?

领导不咋会用maven，他也不想在c盘里搞个文件出来

**Comment by XenoAmess** [comment]
@ElanZh what you need shall be done by maven but not a warpper. 
you shall commit issue like this to apache-maven，but not this porject.

**Comment by ElanZh** [comment]
> 
> 
> @ElanZh what you need shall be done by maven but not a warpper.
> you shall commit issue like this to apache-maven，but not this porject.

I use maven under Windows，maven use setting file by its own path like ``` E:\apache-maven-3.6.0\conf\settings.xml ```，
but maven warpper seems can`t change the default setting file，so I commit this issue

**Comment by Runrioter** [comment]
set maven environment variable

**Comment by mosabua** [comment]
mvnw just calls Maven and then everything .. including what settings file is used and so on is exactly the same as with stock Maven .. as such this issue does not apply. Maven wrapper uses its own Maven installation in ~/.m2/wrapper... so changing the settings file within the distro of course wont have any effect.

In any case .. typically you would change the user settings file in ~/.m2 and NOT the global one with the Maven binary distro

**Comment by ElanZh** [comment]
> 
> 
> mvnw just calls Maven and then everything .. including what settings file is used and so on is exactly the same as with stock Maven .. as such this issue does not apply. Maven wrapper uses its own Maven installation in ~/.m2/wrapper... so changing the settings file within the distro of course wont have any effect.
> 
> In any case .. typically you would change the user settings file in ~/.m2 and NOT the global one with the Maven binary distro

OK,Thanks
