### ISSUE TITLE
MavenWrapperDownloader issue with JDK 7

### ISSUE THREAD

**Issue by teoincontatto** [takari/maven-wrapper#135]
I've found this error while trying running maven wrapper (without the .jar) with an old Oracle JDK 7:

```
$ bash mvnw clean verify -P safer
/builds/ongresinc/scram/.mvn/wrapper/MavenWrapperDownloader.java:104: error: local variable username is accessed from within inner class; needs to be declared final
                    return new PasswordAuthentication(username, password);
                                                      ^
/builds/ongresinc/scram/.mvn/wrapper/MavenWrapperDownloader.java:104: error: local variable password is accessed from within inner class; needs to be declared final
                    return new PasswordAuthentication(username, password);
                                                                ^
2 errors
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```

This is very easy to fix, let me know if you need me to do the PR (if finally you decide this deserve a fix).

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
