### ISSUE TITLE
Add url inside file

### ISSUE THREAD

**Issue by fulldecent** [takari/maven-wrapper#139]
This will help people reference upstream if necessary

**Comment by mosabua** [comment]
What URL in what file?

**Comment by fulldecent** [comment]
In #140 and #141

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.

**Comment by fulldecent** [comment]
Good job! And thanks for the ping.
