### ISSUE TITLE
Version 0.7.6 (readme) vs 0.5.5 (maven repository)

### ISSUE THREAD

**Issue by dragetd** [takari/maven-wrapper#146]
The readme explicitly suggests to install version 0.7.6 with `mvn -N io.takari:maven:0.7.6:wrapper`

In the mvnrepository the latest version is 0.5.5 (https://mvnrepository.com/artifact/io.takari/maven-wrapper)

Funnily enough, using this install command with 0.7.6 does install a version of maven wrapper which then cliams to be 0.5.5.

Can we sync up these numbers somehow?

**Comment by pzygielo** [comment]
@dragetd - but you know [0.7.6](https://github.com/takari/takari-maven-plugin/releases/tag/maven-0.7.6) and [0.5.5](https://github.com/takari/maven-wrapper/releases/tag/maven-wrapper-0.5.5) are two versions of two different things, right?

**Comment by dragetd** [comment]
Ohhh...

The plugin that installs the wrapper and the wrapper itself are two different things. I actually did not realize this. xD

Thanks for clearing it up.
