### ISSUE TITLE
mvnw.cmd properties file parsing bug on win 7

### ISSUE THREAD

**Issue by fblan** [takari/maven-wrapper#153]
jvm.config and maven-wrapper.properties are not parsed in windows 7

the "for /f" command doesn't take '"' around properties file name.
line 114
`for /F "usebackq delims=" %%a in ("%MAVEN_PROJECTBASEDIR%\.mvn\jvm.config") do set JVM_CONFIG_MAVEN_PROPS=!JVM_CONFIG_MAVEN_PROPS! %%a
`
(**"**%MAVEN..... should be (%MAVEN... :
`for /F "usebackq delims=" %%a in (%MAVEN_PROJECTBASEDIR%\.mvn\jvm.config) do set JVM_CONFIG_MAVEN_PROPS=!JVM_CONFIG_MAVEN_PROPS! %%a
` 
Same for line 125
`FOR /F "tokens=1,2 delims==" %%A IN ("%MAVEN_PROJECTBASEDIR%\.mvn\wrapper\maven-wrapper.properties") DO
`
should be 
`FOR /F "tokens=1,2 delims==" %%A IN (%MAVEN_PROJECTBASEDIR%\.mvn\wrapper\maven-wrapper.properties) DO
`
Thanx a lot for your work :)

**Comment by redfish4ktc** [comment]
For the `maven-wrapper.properties` file, see #150 for a fix

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
