### ISSUE TITLE
mvnw.cmd: MVNW_REPOURL variable will never be taken into account

### ISSUE THREAD

**Issue by Og1001** [takari/maven-wrapper#156]
Hello!
In corporate environment with local corporate nexus you have two options:
- setup MVNW_REPOURL var
- or just edit your own copy of mvnw.cmd file

Line 141 will never change DOWNLOAD_URL var. 
Either consider of using 'setlocal EnableDelayedExpansion' (https://ss64.com/nt/delayedexpansion.html) or just introduce additional var for DOWNLOAD_URL in that place.

**Comment by mosabua** [comment]
I am not sure what you are saying ... setting the env var is tested and works just fine.

**Comment by Og1001** [comment]
Sorry, I was not precise enough.

Below steps were checked on Win7 and Win10.

1. Create maven project somehow or take any if you have it. Lets suppose it's located in c:\app
2. Lets suppose we do not have maven in the system, so we install wrapper manually. Download wrapper from https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.tar.gz
3. Unpack it into the root of your app dir and delete wrapper jar C:\prj\app\.mvn\wrapper\maven-wrapper.jar
4. Run this command: **`(set MVNW_VERBOSE=true) && (set MVNW_REPOURL=http://localhost) && mvnw.cmd`**. With this command we emulate corporate env with local nexus instance.
5. Check the output:
C:\prj\app>**`(set MVNW_VERBOSE=true) && (set MVNW_REPOURL=http://localhost) && mvnw.cmd`**

```
Couldn't find "C:\prj\app\.mvn\wrapper\maven-wrapper.jar", downloading it ...
Downloading from: "https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar"
Finished downloading "C:\prj\app\.mvn\wrapper\maven-wrapper.jar"
Takari Maven Wrapper 0.5.6
Detected MVNW_REPOURL environment variable http://localhost
Downloading Maven binary from http://localhost/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.zip
```

As you can see it downloads wrapper jar using predefined URL. MVNW_REPOURL does not affect it.
But wrapper itself as java application takes into account MVNW_REPOURL and works correctly.

6. To fix it add this line:
`setlocal EnableDelayedExpansion`
right after `@echo off` for example
then change line 141         
`echo Downloading from: %DOWNLOAD_URL%`
to
`echo Downloading from: !DOWNLOAD_URL!`
and finally line 148
`"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $webclient.DownloadFile('%DOWNLOAD_URL%', '%WRAPPER_JAR%')"^`
to
`"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $webclient.DownloadFile('!DOWNLOAD_URL!', '%WRAPPER_JAR%')"^`

7. and now  try again:
C:\prj\app>**`(set MVNW_VERBOSE=true) && (set MVNW_REPOURL=http://localhost) && mvnw.cmd`**

```
Couldn't find "C:\prj\app\.mvn\wrapper\maven-wrapper.jar", downloading it ...
Downloading from: "http://localhost/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar"
Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
At line:1 char:282
+ ... pe]::Tls12; $webclient.DownloadFile('http://localhost/io/takari/maven ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Finished downloading "C:\prj\app\.mvn\wrapper\maven-wrapper.jar"
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

Now it works as expected and downloads wrapper jar according to MVNW_REPOURL var.

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
