### ISSUE TITLE
Maven Wrapper can not be installed behind proxy

### ISSUE THREAD

**Issue by gogo-boot** [takari/maven-wrapper#165]
Hi, 

I am trying to install the maven wrapper. 
I can install it from home network. but, I can not install it in company which is behind proxy.

I was wondering and checked the code.  
https://github.com/takari/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
Line 86 : I see that, it just makes a direct internet connection regardless nieder Maven Proxy or Maven Mirror Repo  configuration. 

D:\Project\>mvn -N io.takari:maven:wrapper
[INFO] Scanning for projects...
Downloading from default-maven-3rdparty: 
......
....
Downloaded from default-maven-3rdparty: https://company_repo/artifactory/default-maven-3rdparty/io/takari/graph/takari-graph/0.0.3/takari-graph-0.0.3.jar (173 kB at 351 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.383 s
[INFO] Finished at: 2020-01-10T16:41:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.takari:maven:0.7.7:wrapper (default-cli) on project : Error installing the Maven Wrapper.: Unknown host repo.maven.apache.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mosabua** [comment]
Behind a proxy you are supposed to use the env parameter for installing the wrapper.

https://github.com/takari/maven-wrapper/blob/master/README.md#using-a-maven-repository-manager
