### ISSUE TITLE
maven-wrapper.jar can not be downloaded behind of maven mirror repo

### ISSUE THREAD

**Issue by gogo-boot** [takari/maven-wrapper#166]
Hi,

I have installed successfully by setting MVNW_REPOURL variable from behind proxy.  
But, It doesn't work when the maven-wrapper.jar file is missing. 

mvnw.cmd doesn't use the DOWNLOAD_URL variable properly before excuting the powershell.

I have solved it myself. 
Line 149 : before
`"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $webclient.DownloadFile('%DOWNLOAD_URL%', '%WRAPPER_JAR%')"^`

-----------------------------
Fix
-----------------------------

Add before the IF clause. 
`setlocal EnableDelayedExpansion`

Line 149 : now
`"[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $webclient.DownloadFile('!DOWNLOAD_URL!', '%WRAPPER_JAR%')"^`

Reference
https://stackoverflow.com/questions/9102422/windows-batch-set-inside-if-not-working/9102569

I hope it get fixed in next release.

**Comment by gogo-boot** [comment]
it is same issue as #156

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
