### ISSUE TITLE
initialization error in mac/os 10.15.2 Catalina

### ISSUE THREAD

**Issue by ricard2k** [takari/maven-wrapper#167]
Executing a simple `./mvnw compile`
The result is:
`./mvnw: line 276: /tmp/performanceTests/.mvn/wrapper/maven-wrapper.properties: No such file or directory`
`...some curl stuff...`
`Warning: Failed to create the file `
`Warning: /tmp/performanceTests/.mvn/wrapper/maven-wrapper.jar: No such file or `
`Warning: directory`
`...curl stuff...`
`curl: (23) Failed writing body (0 != 2438)`
`Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain`

Java is installed from homebrew `brew install openjdk@11` and JAVA_HOME variable contains
`/Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home`

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
