### ISSUE TITLE
Configurable maven install directory 

### ISSUE THREAD

**Issue by dantran** [takari/maven-wrapper#17]
My CI env does not allow the build to use its home directory, and maven wrapper is current unpack maven under ~/.m2

**Comment by jvanzyl** [comment]
Where would you like it and how would you like to specify it?

**Comment by dantran** [comment]
we have a conventions to cache this kind of artifacts under top parent's .external-resources.

at jenkins top level parent directory is ${WORKSPACE}

**Comment by jvanzyl** [comment]
Yes, but how would you specify this so that the wrapper understands. An envar?

**Comment by dantran** [comment]
env var sounds reasonable.

**Comment by ppalaga** [comment]
`-Dmaven.user.home=$myDir` is undocumented but works already. Note that the current impl. is a bit picky about the order of command line args: it likes getting sysprops first.

**Comment by mosabua** [comment]
we now have an env var called MVNW_VERBOSE... if you want to do something similar for the install feel free to send a PR @dantran ;-)

**Comment by TylerLu** [comment]
I scrutinized the source code and solved this by setting the **MAVEN_USER_HOME** environment variable. I am working on Azure:
`set MAVEN_USER_HOME=D:\home\site\deployments\tools\maven`

**Comment by mosabua** [comment]
See https://www.lewuathe.com/maven-wrapper-home.html

**Comment by mosabua** [comment]
I added this to the README docs now.
