### ISSUE TITLE
./mvnw: Warning should be logged to stderr

### ISSUE THREAD

**Issue by fknittel** [takari/maven-wrapper#170]
When the JAVA_HOME environment variable is not set, the warning is logged to stdout although it is best practice to log errors/warnings to stderr. Please replace

https://github.com/takari/maven-wrapper/blob/329e64a30c5f3a892267eb6ccb449c7e273aee24/mvnw#L159

with

```sh
echo "Warning: JAVA_HOME environment variable is not set." >&2
```

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
