### ISSUE TITLE
Maven wrapper fails when there are spaces in arguments.

### ISSUE THREAD

**Issue by ProggerPete** [takari/maven-wrapper#23]
This works:

mvn com.smartcodeltd:release-candidate-maven-plugin:version "-DoutputTemplate=##teamcity[setParameter name='env.PROJECT_VERSION' value='{{ version }}']"

This does not:

./mvnw com.smartcodeltd:release-candidate-maven-plugin:version "-DoutputTemplate=##teamcity[setParameter name='env.PROJECT_VERSION' value='{{ version }}']"

The error is 

[ERROR] Unknown lifecycle phase "name='env.PROJECT_VERSION'". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

Both the installed and wrapper versions of Maven are 3.3.9

**Comment by ProggerPete** [comment]
This issue has caused me to abandon using maven-wrapper.

**Comment by mosabua** [comment]
Fixed with upcoming 0.2.0 release
