### ISSUE TITLE
download maven-wrapper.jar within the script

### ISSUE THREAD

**Issue by clebertsuconic** [takari/maven-wrapper#24]
Wouldn't be possible to download the jar with curl if the jar is not available?

This could be a patch on the script.

``` bsh
if [ ! -f $MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar ]; then
    curl -o $MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar http://central.maven.org/maven2/io/takari/maven-wrapper/0.1.4/maven-wrapper-0.1.4.jar
fi
```

the same would have to be done on the .cmd

Someone just submitted a pr on Apache artemis using this wrapper, and the first question that came to mind was the wrapper.jar that would have to be commited as part of the source code.

**Comment by jvanzyl** [comment]
This would assume curl is available, which may not be the case on many Windows systems I would imagine.

**Comment by clebertsuconic** [comment]
well.. if not available.. then nothing you can do... just show an error
I was just wondering for an additional possibility.

**Comment by clebertsuconic** [comment]
Can you look at how we did at artemis?

https://github.com/apache/activemq-artemis

The source distribution is removing mvnw as it was my understanding to remove compiled dependencies from the apache distribution (accordingly to apache rules).

If there was a curl to download the jars, we could keep it on the source distr (it would be requiring curl dependency on that case, but that's acceptable IMO).

**Comment by gzm55** [comment]
+1 to this issue, we could download this bootstsrap binary on the fly with two methods:

a) **use os specific binary**: on non-windows, try wget and curl; on windows, try bitsadmin.exe. this will cover most cases, and just a little lines of codes.
b) since we require jdk to startup the maven process, we can just **depend on the jdk api** to download wrapper jar, that is, cat the downloading java coda into a tmp file, compile to the bootstrap.class, then run to download.

sample codes for method b)

> import java.net.\*;
> import java.io.\*;
> import java.nio.channels.\*;
> 
> public class MVNW_Bootstrap {
>   public static void main(String args[]) {
>     String url="http://central.maven.org/maven2/io/takari/maven-wrapper/0.1.4/maven-wrapper-0.1.4.jar";
>     downloadFileFromURL(url, new File("./test.jar"));
>   }
>   public static void downloadFileFromURL(String urlString, File destination) {
>       try {
>           URL website = new URL(urlString);
>           ReadableByteChannel rbc;
>           rbc = Channels.newChannel(website.openStream());
>           FileOutputStream fos = new FileOutputStream(destination);
>           fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
>           fos.close();
>           rbc.close();
>       } catch (Throwable e) {
>           e.printStackTrace();
>       }
>   }
> }
>

**Comment by chrisdutz** [comment]
As its a strict Apache policy to not have binary artifacts in releases, I too would like to see a way to use the maven wrapper without having to check-in anything binary ... I particularly like the idea of using Java to achieve this. I guess the boilerplate code to compile this one class should be quite minimal.

**Comment by gzm55** [comment]
how about the way described about half year ago, for all platform:

> add .mvnw/maven-wrapp/bootstrap0.java
> if not exists ~/.m2/maven-wrapper.jar, then
>   find javac and java
>   compile bootstrap0.java to ~/.m2/maven-wrapper-downloader.class
>   run ~/.m2/maven-wrapper-downloader.class to download ~/.m2/maven-wrapper.jar

**Comment by chrisdutz** [comment]
Working on it ... https://github.com/chrisdutz/maven-wrapper/commit/b0487654b032ee59446919f22c01c2235d8c4e93

**Comment by mosabua** [comment]
If you get this cleaned up I am happy to pull this in @chrisdutz

**Comment by chrisdutz** [comment]
Ok ... so I updated the linux version again to test curl, wget and to fallback to java if none of them exist. Next I'll try to do the same/similar for the windows command.

**Comment by chrisdutz** [comment]
https://github.com/takari/maven-wrapper/pull/60

**Comment by davidrabinowitz** [comment]
+1

**Comment by mosabua** [comment]
This is now merged, improved and release with Maven Wrapper 0.4.0 and used in the plugin 0.6.0 (also released).

**Comment by fbricon** [comment]
Any reason why the maven-wrapper.jar is still added to the project by default?

**Comment by mosabua** [comment]
Yes... its easier for users and he default supported use case we had in the past. Maybe its really stable and well tested we can change that .. but I am weary to do that now ..
