### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by imgx64** [takari/maven-wrapper#26]
The [latest release of io.takari:maven](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.takari%22%20AND%20a%3A%22maven%22) on Maven Central was 9 months ago on 26-Oct-2015. I think it's time for a new release so we can use `mvn -N io.takari:maven:wrapper` instead of copy-pasting files.

(I need a more recent release because of [this patch](https://github.com/takari/maven-wrapper/commit/69f3c6dd1b07620f28c1fc8cb20e392afcd9e95b), which fixed maven-wrapper in Cygwin).

**Comment by Gengar003** [comment]
I, too, would like a new release. I'm eagerly waiting on [this patch](https://github.com/takari/maven-wrapper/commit/a1ca6a9f940155437dbb9bea049cb4d488153486) so my company doesn't have to fix each `mvnw` by hand after adding it to a project...

**Comment by jvanzyl** [comment]
Wrapper and Takari Maven Plugin released to Maven Central, should be there shortly.
