### ISSUE TITLE
Apparent inconsistencies regarding command line options

### ISSUE THREAD

**Issue by dsyer** [takari/maven-wrapper#3]
The Un*X script has this:

```
MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG $@"
export MAVEN_CMD_LINE_ARGS
...
exec "$JAVACMD"  ... "$@"
```

I.e. `MAVEN_CONFIG` are added to the env var but not used in the actual command line.

The windows one has this:

```
set MAVEN_CMD_LINE_ARGS=%*

...
%MAVEN_JAVA_EXE% ... %MAVEN_CMD_LINE_ARGS%
```

I.e. `MAVEN_CONFIG` is ignored, but the env var is used on the command line.

I'm happy to fix it and send a PR if you can provide some guidance on what the actual intent was.

Also, what I ultimately want, which could be more of a discussion, I don't know, is to be able to change the maven command line arguments from a file that I can put in source control. I see that might be dangerous if the user wants to override it, but this is my current best hope to get a build that works for everyone out of the box, and yet doesn't have repositories (and distribution management) hard-coded in poms.

**Comment by spencergibb** [comment]
@dsyer maybe we could add something like this to the already existing block

```
if [ -z "$MAVEN_SKIP_RC" ] ; then

  if [ -f /etc/mavenrc ] ; then
    . /etc/mavenrc
  fi

  if [ -f "$HOME/.mavenrc" ] ; then
    . "$HOME/.mavenrc"
  fi
#new current dir check
  if [ -f "./.mavenrc" ] ; then
    . "./.mavenrc"
  fi

fi
```

That way they can opt out if they set `MAVEN_SKIP_RC` and we can check `./.mavenrc` into src control.
An alternative to `./.mavenrc` could be `./.mvn/mavenrc` (since `.mvn` is already checked in to src control.

**Comment by jvanzyl** [comment]
We already have a mechanism for checking in a source file with command line arguments. There are some details here:

http://blog.soebes.de/blog/2015/03/17/apache-maven-3-dot-3-1-features/

**Comment by spencergibb** [comment]
@jvanzyl sweet: `${maven.projectBasedir}/.mvn/maven.config` and `${maven.projectBasedir}/.mvn/jvm.config` and we can enforce the maven version with maven-wrapper.

**Comment by bshannon** [comment]
One of the original issues reported here (that MAVEN_CONFIG is ignored) doesn't seem to have been fixed.  Should this issue be reopened?
