### ISSUE TITLE
mvnw doesn't escape directory in find_maven_basedir and MAVEN_PROJECTBASEDIR

### ISSUE THREAD

**Issue by etki** [takari/maven-wrapper#31]
Hi.

I've noticed that maven wrapper doesn't use double quotes in find_maven_basedir/$MAVEN_PROJECTBASEDIR, so if current directory contains spaces, it will result in malformed computation.

I'm not sure how this project is managed (is mvnw somehow generated), so i didn't fork and send pull request

**Comment by mosabua** [comment]
Coming in release soon..

**Comment by mosabua** [comment]
Fyi maven-wrapper:0.2.0 and and takari-maven-plugin:0.4.0 are released to Central.
