### ISSUE TITLE
mvnw does not handle MAVEN_PROJECTBASEDIR being root of a drive

### ISSUE THREAD

**Issue by bjhargrave** [takari/maven-wrapper#32]
Using `subst` to set a drive letter to the folder holding my project and building from that drive letter (`T:\`)will result in 

```
set MAVEN_PROJECTBASEDIR=T:\
```

This causes WRAPPER_JAR to be malformed

```
set WRAPPER_JAR=""T:\\.mvn\wrapper\maven-wrapper.jar""
```

The java execution then fails with java displaying a usage message.

```
"C:\Program Files\Java\jdk1.7.0\bin\java.exe"    -classpath ""T:\\.mvn\wrapper\maven-wrapper.jar"" "-Dmaven.multiModuleProjectDirectory=T:\" org.apache.maven.wrapper.MavenWrapperMain  
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
```

**Comment by bjhargrave** [comment]
Actually the issue is in 

```
"-Dmaven.multiModuleProjectDirectory=%MAVEN_PROJECTBASEDIR%"
```

when `MAVEN_PROJECTBASEDIR=T:\`. The trailing backslash breaks the command line parsing...

```
"-Dmaven.multiModuleProjectDirectory=T:\"
```

**Comment by bjhargrave** [comment]
I will also note that this problem is also present in the maven-invoker-plugin when it execs a child JVM to run maven, so perhaps you just cannot have a maven project in the root of a drive on windows...

**Comment by mosabua** [comment]
This is a problem across all of Maven I think and hence will not try to support this in the wrapper.
