### ISSUE TITLE
Typo in comment in mvnw.cmd causes script to fail

### ISSUE THREAD

**Issue by jvz** [takari/maven-wrapper#35]
In mvnw.cmd, there is a comment that starts with `#` instead of `@REM` which causes the script to fail on Windows Server 2002 (and probably other versions).

**Comment by fbricon** [comment]
Should be fixed with  https://github.com/takari/maven-wrapper/pull/27

**Comment by mosabua** [comment]
Fyi maven-wrapper:0.2.0 and and takari-maven-plugin:0.4.0 are released to Central.
