### ISSUE TITLE
how to modify maven

### ISSUE THREAD

**Issue by binkley** [takari/maven-wrapper#38]
This may be a documentation issue.  I wasn't able to see how to modify the maven installation downloaded by `mvnw`.  For the regular system-wide maven installation, I usually update it with Guy's excellent "maven color" changes (https://github.com/jcgay/maven-color) which requires switching logback from the "simple" implementation to the "classic" one.

Suggestions?

**Comment by mosabua** [comment]
See the bottom of the readme at https://github.com/takari/maven-wrapper

**Comment by binkley** [comment]
Right, I read that with interest.  I'm not looking to change my maven downloaded ZIP, just swap out some files in an already downloaded distro.  Is this too specific to my own tastes?

**Comment by fbricon** [comment]
@binkley the point of the wrapper is to provide consistent maven distro for anyone using your project. The wrapper doesn't provide any way to modify an existing version of Maven.

So you probably want to create your modified version of a Maven distro, publish it somewhere, then you'll just have to make sure your project points to that custom distro in .mvn/wrapper/maven-wrapper.properties

**Comment by fbricon** [comment]
I now recall I actually wrote a groovy script some time ago that'd modify an existing Maven distro and update it to support colorized output. 

See https://gist.github.com/fbricon/5763949. It's most likely outdated and certainly won't work with 3.3.9, but should give you a idea of how to do it.

**Comment by mosabua** [comment]
Also keep in mind that Apache Maven 3.5.0 is just about to be released and it has syntax highlighting by default enabled so you wont have to modify anything....
