### ISSUE TITLE
launcher does not support maven 2.2.1

### ISSUE THREAD

**Issue by radai-rosenblatt** [takari/maven-wrapper#42]
i can generate the wrapper just fine
```
$ mvn -N io.takari:maven:wrapper -Dmaven=2.2.1
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Avro Toplevel 1.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven:0.3.4:wrapper (default-cli) @ avro-toplevel ---
[INFO] 
[INFO] The Maven Wrapper has been successfully setup for your project.
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```
but when i try to run it:
```
$ ./mvnw clean
Exception in thread "main" java.lang.RuntimeException: Could not locate the Maven launcher JAR in Maven distribution '/home/user/.m2/wrapper/dists/apache-maven-2.2.1-bin/734vqac49jfbm96jf0vlddftns/apache-maven-2.2.1'.
	at org.apache.maven.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:50)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:28)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
```

looking at the maven 2.2.1 distribution it doesnt have plexus-classworlds-*.jar which the wrapper expects. instead it has /lib/maven-2.2.1-uber.jar

**Comment by mosabua** [comment]
See my comments in https://github.com/takari/maven-wrapper/pull/41 .. I do not believe we should support Maven 2.

**Comment by radai-rosenblatt** [comment]
the problem is with older projects. for example - i found this while trying to add a wrapper to https://github.com/apache/avro. their minimum supported maven version is 2.2.1, which i suspect they'd be reluctant to bump up. while you could add a wrapper to such a project that would use newer maven, that might introduce compatibility issues if things work with the wrapper but dont work under the officially supported minimum version

**Comment by mosabua** [comment]
They should upgrade to Maven 3 .. 2.2.1 was released in 2009 and has been unmaintained ever since. Thats essentially an eternity ago. By adding the wrapper you are not really helping them. You probably run into other issues anyway.

**Comment by mosabua** [comment]
Also what makes you think that 2.2.1 is the minimum version they support anyway? If you are talking about prerequisites.. that is NOT what it does...

**Comment by radai-rosenblatt** [comment]
https://github.com/apache/avro/pull/215
lets see :-)

**Comment by mosabua** [comment]
I just ran the avro build with Maven 3.5.0 and it worked just fine. So there is no need from that perspective.
