### ISSUE TITLE
Document how to upgrade maven wrapper

### ISSUE THREAD

**Issue by ttddyy** [takari/maven-wrapper#43]
It seems maven wrapper 0.2.0 has released. 
What is the proper way of upgrading existing maven wrapper?

it seems running this upgrades the local maven wrapper files.
```mvn -N io.takari:maven:wrapper```

It would be good if this is documented.

**Comment by mosabua** [comment]
Fixed via https://github.com/takari/takari-maven-plugin/commit/0fb865712445d14f4526c6fef2da1efbdc067d85 and https://github.com/takari/maven-wrapper/commit/b2305e1af4feadfb4225d4567e96f83ca382733c
