### ISSUE TITLE
Means to check current maven wrapper version

### ISSUE THREAD

**Issue by ttddyy** [takari/maven-wrapper#44]
Is there any way to check current version of maven wrapper?

maybe `./mvnw --version` to include maven wrapper version??

**Comment by mosabua** [comment]
There is no simple way like that but you could look at the contents of the jar file 

cd .mvn/wrapper/maven-wrapper.jar.

jar xf maven-wrapper.jar

cat META-INF/MANIFEST.MF 

Manifest-Version: 1.0
Implementation-Title: maven-wrapper
Implementation-Version: 0.2.0
Archiver-Version: Provisio Archiver
Built-By: manfred
Specification-Title: maven-wrapper
Implementation-Vendor-Id: io.takari
Created-By: Takari Inc.
Build-Jdk: 1.8.0_121
Specification-Version: 0.2.0

I dont think anything simpler is needed to be honest. But if you want you can send a PR
