### ISSUE TITLE
Unignore files from gitignore

### ISSUE THREAD

**Issue by TroyMass** [takari/maven-wrapper#50]
Often in a project the top level gitignore will include `*.jar` which will exclude all jar files. But the `maven-wrapper.jar` needs to be un-ignored.

gitignore files are specific to the directory they are in and the subdirectories. So you could generate a `.mvn/wrapper/.gitignore` file which would explicitly un-ignore these files. The contents of this file would look like:

    !maven-wrapper.jar
    !maven-wrapper.properties

**Comment by mosabua** [comment]
Typically in a Maven projec the top level ignore would just set target to ignore imho and not *.jar ..

**Comment by mosabua** [comment]
Also this makes the setup specific to git and even a specific usage of git and its ignore file. To be honest I think thats what the users should manage themselves (if they even need to).

**Comment by TroyMass** [comment]
It is a little unrelated to maven, but git is pretty common and I've seen a lot of projects ignore both `target` and `*.jar`. It could automatically check to see if it is a git project and only add the gitignore if its relevant.

**Comment by mosabua** [comment]
This seems to make it overly complicated. If you send a PR that is clean and simple I might consider it but I am not going to implement myself.. closing for now.
