### ISSUE TITLE
Maven wrapper dosen't allow to override local configuration from .mvn/maven.config

### ISSUE THREAD

**Issue by mariuszs** [takari/maven-wrapper#51]
Standalone maven allow to override configuration from `maven.config`, but maven wrapper does not.

This issue is described in ~~https://issues.apache.org/jira/browse/MNG-5930~~ https://issues.apache.org/jira/browse/MNG-6235

**Comment by mosabua** [comment]
I am not sure what you are saying but the usage of maven.config from the wrapper works just fine and as intended. The linked ticket talks about env variable expansion which does work in either usage ... can you clarify?

**Comment by mariuszs** [comment]
Ok, I have project with `pom.xml`

```...   
    <version>${revision}</version>
```

and `.mvn/maven.config`:

```-Drevision=1.0.0-SNAPSHOT```

When I invoke maven:

```
mvn  package -Drevision=2.0.0-SNAPSHOT 
...
[INFO] Building FOO 2.0.0-SNAPSHOT
```

but when I use wrapper:

```
./mvnw package -Drevision=2.0.0-SNAPSHOT
...
[INFO] Building FOO 1.0.0-SNAPSHOT
```

**Comment by mariuszs** [comment]
Sorry, maven wrapper was older (3.3.9), and linked to wrong ticket... 💩

**Comment by mosabua** [comment]
Good thing I did a new release recently then ;-)
