### ISSUE TITLE
Extraneous output breaks parsing Maven output

### ISSUE THREAD

**Issue by Gengar003** [takari/maven-wrapper#52]
This line in `mvnw`: https://github.com/takari/maven-wrapper/commit/2fea7af95512940335c593751517abf67beab1f5#diff-7f6d424362f5b03d9b91a80a1e43eefeR200

Breaks scripts that may have been trying to parse the output of a Maven command kicked off with maven-wrapper (e.g. `mvn help:execute ...` to extract properties from a project) by introducing an unexpected, non-maven / non-formatted line of output.

It looks like it was just left in after adding a new feature...?

Please remove it.

**Comment by mosabua** [comment]
This was added in on purpose to help with user troubleshooting and at this stage I plan to leave it in place. There is also an output of Maven wrapper version in the log now so you will have to adjust your parsing of the output. Generally doing that is not really a good idea anyway...

**Comment by Gengar003** [comment]
Please remove it. `maven-wrapper` introducing additional output instead of just wrapping maven _as the default behavior_ is not desirable.

I do not want to update my parsing of maven output to parse non-maven things because

1. I now have to handle both raw `mvn` and `mvnw` output - which means I must now _detect where the input to parse came from_ - whereas before I could trust that the output would not be changed by maven-wrapper.
2. I cannot trust that `mvnw` will not add or change its additional output in the future, meaning I must abandon it for any tasks where I need to process the output of a Maven build.

**Comment by mosabua** [comment]
If your parsing is robust it should not matter how the log starts. The additional output from the wrapper is useful and was requested from numerous users. 

You do not need to abandon using the wrapper.. you just need to fix your parsing. You might also have to adapt it to the color output from Maven 3.5.0 for example. In either case .. parsing log output should probably be avoided...

At this stage I am not convinced removing the output is useful. Anybody from @takari/contributors want to chime in? 

Fyi the other output coming is showing wrapper version - https://github.com/takari/maven-wrapper/commit/dd9d47e0f637d80813d6dc58a9f422ba0215a6f7

**Comment by Gengar003** [comment]
The problem for me is that I am building tools that other developers/teams will bring projects and/or project output to, and I need to understand/parse their output.

Previously, it didn't matter whether they used `mvn` or `mvnw`, nor which version of `mvnw` they used - the output was the same.

Now, with additional output added only to `mvnw` and more output coming, it's additional work to distinguish desired parts of the actual maven output, from stuff that `mvnw` adds on. In order to reliably filter out additional `mvnw` output that was not generated by the software being built, my parsing needs to know 

1. which version of `mvnw` (if any) was used to generate the output
2. which output was added in which version of `mvnw`
3. the actual values of the output that `mvnw` would add - otherwise it may be mistaken for interesting output from the real maven logs - this means my parsing needs to compute these values itself _which may not always be possible_ if the parsing is not happening in the same environment with the same source that generated the output.

If there were a way to turn on this "debug" output in maven-wrapper - either through a command-line flag or an ENVVAR or something, it would not cause problems for my use-case as long as it was off by default.

**Comment by ttddyy** [comment]
How about adding section divider that indicates where the output came from.

e.g:
```
> ./mvnw compile
/Users/ttddyy/repo/abc
Takari Maven Wrapper: 0.1.5
=======  <== some divider/horizontal line
// whatever maven output...

```

Then, further `mvnw` output addition should not cause any issue to the script.

**Comment by Gengar003** [comment]
For what it's worth, at least one developer - myself - did not have any problem that the extra output solved.

However, I now have lots of extra work to update everything that was parsing _maven_ output to now disambiguate between _mvn_ and _mvnw_ output and continue to parse accordingly.

Dividers and formatting don't help unless I have a canonical way for my parsers to detect which `mvnw` version is in use and shape of extra output it will produce. Without that, I can't guarantee that I can separate the `mvnw` output from something that the real `mvn` build might have printed.

An immediate objection to a horizontal line of `====..` is that some of my developers' builds use that in their output around error messages. It's likely that any other choice of divider will similarly be "real" output of someone else's build, too.

I've said my piece and will leave y'all to it - I still strongly believe that the _default_ action being "add extra output to the Maven output" leads to a worse user experience.

**Comment by ttddyy** [comment]
Divider can be as simple as `#=== MVN WRAPPER OUTPUT ===`, `#=== MVN OUPUT ===`, etc. which I don't think developer would use, though not 100% guaranteed.

Another alternative I think is:
Wherever printing out `mvnw` info(basedir and version), add if condition to enable printing out such info.(e.g: check system variable, etc).
Then, provide `mvnw-with-info` command that sets such flag(system variable) and delegates to `mvnw`.

Or, simply hidden flag(system variable or command argument) such as `MVNW_ENABLE_INFO`...
Initially this idea was not agreed since it introduces `mvnw` specific variable(or parameter). see #48.
However, such flag might be a viable option due to the complaints for always printing `mvnw` info(basedir and version).

**Comment by kutzi** [comment]
I also think that the extra output should be removed.
The maven wrapper should behave 100% as pure mvn and not add or remove anything.

**Comment by mosabua** [comment]
Just fyi everyone ... we will take the output out in the next release and have some sort of option to make it verbose but have it off by default. I just have to implement and cut a release.. but that will take a bit due to the upcoming holiday and such.
