### ISSUE TITLE
Configuring maven wrapper local repository

### ISSUE THREAD

**Issue by baneeishaque** [takari/maven-wrapper#57]
I already configured local repository using <localRepository> in setting.xml file under my M2_HOME/conf folder. it is `<localRepository>D:/Programs/maven_repository</localRepository>` . With mvn command, custom local repository works fine. but the mvnw command ( i am on windows 7 64 bit with maven 3.5.0), always uses default local repository, _${user.home}/.m2_ ( _C:\Users\prism\.m2_ in my case). Is there any option to use custom local repository with maven wrapper?

**Comment by mosabua** [comment]
This is not correct. The Maven invocation via the wrapper honours and uses all settings.xml content including a changed path to a local maven repo. The only place for which it does NOT use the local repo is the initial download of the Maven repo. This happens before Maven is invoked and hence before any settings is parsed and understood. The configuration for that path in in the wrapper.properties file...

**Comment by baneeishaque** [comment]
what are settings that can be controlled by wrapper.properties file?
Is <localRepository> can be controlled ( then i can use that folder for initial download)?

**Comment by mosabua** [comment]
It only contains the URL to use for downloading the maven distro. E.g. see https://github.com/takari/maven-wrapper/blob/master/.mvn/wrapper/maven-wrapper.properties

Once that is downloaded it starts normal maven and everything behaves as usual

**Comment by baneeishaque** [comment]
OK, i got that...

## Problem
**The problem is that on first run (using _mvnw clean package_ on my project root) - maven distribution downloaded and extracted to default maven repository under folder wrapper ( that is fine), then this extracted maven distribution is used for the execution. this extracted maven distribution caches on default maven repository.
Reason : local repository entry is not added to the settings.xml file of this newly downloaded maven distribution.** 

## Here is my solutions... 
**Solution1 : Instead of using _mvnw clean package_, _mvn clean package_ is used. then system globally installed maven is used by avoiding maven wrapper. system globally installed maven caches to custom local repository because it is aware about it. _But it needs a maven installation on the system and against the objectives of the maven wrapper._**

**Solution 2 :** I edited the distribution URL to my file system like this : file\:/C:/Programs/maven_repository/apache-maven-3.5.0-bin.zip . So, it downloaded quickly from my filesystem and extracted to default maven home (optional - can avoided in a internet connected system). **After extraction i killed the process, then i geos to settings.xml file on the extracted maven distribution ( lies under defualt maven home/wrapper) and added an entry for my custom local maven repository (now, the downloaded maven distribution is aware about my custom local repository). Then i again run _mvnw clean package_ on my project root. At this time, the previously extracted wrapper is reused and my custom local repository is used for caching.**

## Can you automate solution2 like this...
**_Specify maven local repository on wrapper.properties ( something like localRepository=D:/Programs/maven_repository), after extraction - the settings.xml file of the newly extracted maven distribution will be edited to include this custom local repository entry - after that exectuion proceeds._**
Alternative : Specify maven local repository in an environment variable (something like M2_LOCAL_REPOSITORY), the wrapper always uses this variable to find maven local repository folder. (can you please implement the alternative approach on maven too, then we can automate the manual editing of settings.xml file on global maven installation?)

**Comment by mosabua** [comment]
I really dont understand what you are trying to achieve. Your solutions dont make sense to me at all. If you have Maven already local on your filesystem then you dont need to use the wrapper. And the settings file will automatically be used if it exists not matter if you invoke mvn or mvnw .. 

What is the actual problem you are trying to solve?

**Comment by DenEwout** [comment]
I'm trying to figure out the same thing. I agree that the "solutions" above don't make sense, but here is my usecase. Maven is installed on a build server, which has the local repository configured (in M2_HOME/conf/settings.xml) on a separate data partition.

My project on the same build server uses mvnw, because I require a different maven version from the installed one and I want to encapsulate the maven version/build setup within my project. From your previous comments you suggest that mvnw should respect any already installed maven's configuration, but this does not seem to be the case.

How do I run mvnw so that it uses a different folder than /home/%USER%/.m2?

Kind Regards,
Ewout.
  
**Edit:** For now I symlinked the folders to where they should go and this seems to work fine.
