### ISSUE TITLE
Support MAVEN_ARGS

### ISSUE THREAD

**Issue by bsideup** [takari/maven-wrapper#62]
Hi!

It would be nice if Maven Wrapper would support MAVEN_ARGS:
https://github.com/apache/maven/blob/811b8f52f9dd897267f7a57656f84810827a3121/apache-maven/src/bin/mvn#L34

it's very handy to set some defaults.

Thanks!

**Comment by mosabua** [comment]
What makes you think MAVEN_ARGS is not supported?

**Comment by atanasenko** [comment]
MAVEN_OPTS are supported, not sure about MAVEN_ARGS

**Comment by atanasenko** [comment]
That link above seems to be some old fork of maven with support for that.
But for a particular pom, you could configure default goals under <build>/<defaultGoal>

**Comment by mosabua** [comment]
I think MAVEN_ARGS are generally deprecated.. you can always use .mvn folder level config for jvm and maven..

**Comment by mosabua** [comment]
Let us know if you want to achieve something specifically..

**Comment by bsideup** [comment]
@atanasenko 
I fixed the link, but now I see that it was removed. 

It's sad because it would be very helpful for the scenarios like Travis:
```
lang: java
env:
    - MAVEN_ARGs="-P-commercial_features"
```

currently, just because of the profiles, we have to override both `install` and `script` phases

**Comment by mosabua** [comment]
you can set that up easily in your .mvn/maven.config with the project. No need to change anything.
