### ISSUE TITLE
Promote Maven Wrapper feature request in README.md

### ISSUE THREAD

**Issue by fabriziocucci** [takari/maven-wrapper#64]
Assuming that feature requests for Maven are mainly prioritized by votes, I guess one of the reasons why the Maven Wrapper is not "official" yet is because there are only a couple of votes in the corresponding [Maven Wrapper feature request](https://issues.apache.org/jira/browse/MNG-5937).

Wouldn't it be nice to promote the feature request by adding a direct link in the `README.md`?

**Comment by mosabua** [comment]
Not really. We are perfectly happy to manage the project outside the ASF even though most of us are also Maven committers.
