### ISSUE TITLE
Update to Maven 3.5.2 -- fix color issue for Cygwin / MinGW

### ISSUE THREAD

**Issue by binkley** [takari/maven-wrapper#68]
https://issues.apache.org/jira/browse/MNG-6242

To support color Maven output, update to Maven 3.5.2, and/or update the wrapper scripts along these lines (diff for `mvnw`):

```
211a212,219
> # detect cygwin or mingw pseudo-terminal for Jansi
> # workaround for https://github.com/fusesource/jansi-native/issues/11
> if $cygwin || $mingw; then
>   if [ -t 1 ]; then
>     MAVEN_OPTS="-Djansi.passthrough=true $MAVEN_OPTS"
>   fi
> fi
>
```

**Comment by mosabua** [comment]
Thanks for the tip.. I am in the process of getting to a release including usage of 3.5.2..

**Comment by mosabua** [comment]
Latest version is already at 3.5.2  and it seems to work fine. You think we need to add that anyway

**Comment by binkley** [comment]
@mosabua Right.  I needed to add that bit into the wrapper script.  The key issue is Jansi does not recognize Cygwin as supporting ANSI escape codes (the Java code in Jansi detects the Windows platform, and disables support for the codes).  But if the `-Djansi.passthrough` flag is set to `true`, Jansi ignores platform-detection, and prints the escape codes.

This has to be done in the wrapper script (same as Maven 3.5.2 is now doing in it's script).

**Comment by unlimitedsola** [comment]
btw is the 3.5.2 default? any plan to update to the latest release?

**Comment by mosabua** [comment]
Just released a new version with support for avoid the jar in the repo. Can you send a PR for this issue now?

**Comment by binkley** [comment]
This is addressed for me in Maven 3.5.3, with their upgrade in the JAnsi dependency.

**Comment by PeterDaveHello** [comment]
Maven v3.5.3 released with color output fixes:
 - https://maven.apache.org/docs/3.5.3/release-notes.html

I just sent a PR  #79 to upgrade it!

**Comment by mosabua** [comment]
Upgraded to 3.5.4 now
