### ISSUE TITLE
Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check 

### ISSUE THREAD

**Issue by gordonGin** [takari/maven-wrapper#69]
Hi there, 

I want to use your wrapper but after running the "mvn -N io.takari:maven:wrapper"  instruction i'm i've starded to get the error below. Why is the wrapper activating apache rat?

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail: Too many files with unapproved license: 1 See RAT report in: /Users/pimparic/projects/aem-sample-we-retail/target/rat.txt -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail: Too many files with unapproved license: 1 See RAT report in: /Users/pimparic/projects/aem-sample-we-retail/target/rat.txt

Regards, 
Ricardo

**Comment by mosabua** [comment]
The wrapper does nothing in the aspect. With your description we can not tell but you project must have changed.
