### ISSUE TITLE
Allow specifying Maven extensions

### ISSUE THREAD

**Issue by axelfontaine** [takari/maven-wrapper#71]
Maven extensions can be dropped in the `MVN_HOME/lib/ext` directory. They are very useful for things like custom wagons (S3, ...). It would be great to be able to specify the Maven coordinates of the extension jars that should be downloaded and dropped in that directory.

**Comment by mosabua** [comment]
This will not be supported since Maven extensions should be specified in the .mvn/extensions.xml nowadays and NOT be copied into the lib/ext folder. E.g. see https://github.com/takari/polyglot-maven-examples/blob/master/ruby/.mvn/extensions.xml

**Comment by axelfontaine** [comment]
Thanks! That works indeed. It would be great to add this to the docs as there currently really isn't an easy way to discover this. This should be and afaik is in the Maven docs..
