### ISSUE TITLE
The wrapper now downloads source files in the .mvn/wrapper directory

### ISSUE THREAD

**Issue by gsmet** [takari/maven-wrapper#72]
Hi,

Starting this morning (and I didn't have builds running for a few days so I think it must be a regression in the latest release), my Travis builds fail because I have a license checking plugin and the Maven wrapper starts to download some source files:
```
[INFO] Checking licenses...
[WARNING] Missing header in: /home/travis/build/gsmet/hibernate-validator/.mvn/wrapper/MavenWrapperDownloader.java
```

Is this something expected? I will ignore these files in my license check but it looks like a bug.

Thanks.

**Comment by fbricon** [comment]
This file is part of a new feature which does not require you to keep the maven wrapper jar in your SCM anymore. See #70. If the jar is missing, and no download utility is found in the system, this source file will be compiled to download the jar.
So you just need to exclude this source from further analysis.

**Comment by gsmet** [comment]
OK, that's what I did this morning, just wanted to be sure it was a desired behavior.

Thanks for confirming and sorry for the noise.
