### ISSUE TITLE
Add feature to download of a specific version of the JDK

### ISSUE THREAD

**Issue by Zlika** [takari/maven-wrapper#75]
Hi!

The first line of the README states that "The Maven Wrapper is an easy way to ensure a user of your Maven build has everything necessary to run your Maven build". However there is a huge thing missing: the JDK itself!
It would be SO cool to be able to specify a given version of the JDK to use during the maven build, and let Maven Wrapper automatically download it. Such a feature would also be very interesting to have reproducible builds (cf. [Reproducible/Verifiable Builds](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=74682318) on the Apache Maven wiki).
The implementation could reuse [JdkGet](https://github.com/takari/jdkget).

What to you think about such a feature?

Regards

**Comment by mosabua** [comment]
This can be done with tools such as JDKGet .. we will however NOT add this as a feature to the Maven wrapper as this goes beyond its scope..

https://github.com/takari/jdkget
