### ISSUE TITLE
boot behavior of the script 'mvnw' is out of sync with the original 'mvn'

### ISSUE THREAD

**Issue by gzm55** [takari/maven-wrapper#76]
Hi, I think the entry scripts `mvnw{,.cmd}` take much codes of the original `mvn{,.cmd}` and use own wrapper launcher to replace plexus launcher in order to do some provision actions. So the behavior of mvnw + wrapper_launcher should be almost the same as mvn + plexus_launcher.

From maven 3.5.0, `M2_HOME` is removed, and the property `library.jansi.path` is set, but our `mvnw` is not followed up. So we need to sync mvnw to the default maven dist (3.5.0+).

Here is two solutions:

- a) manually update codes of `mvnw` and wrapper launcher to mimic the boot progress of our selected maven version (3.5.2 now), and each time we update the default maven, we should do this again.
- b) do little refactor, wrapper only assemble the dist path and optionally downloads/install the maven dist, then `exec` into the original `mvn`

Personally I prefer b), the boot behavior is always sync to selected maven version by user and wrapper project is more simpler; the only cons may be that on some machine without `md5sum` command, we have to execute an additional `java` process to assemble the maven home.

**Comment by mosabua** [comment]
Does this still apply? Released maven-wrapper 0.5.0 and takari-maven-plugin 0.7.0

**Comment by gzm55** [comment]
still apply.

**Comment by mosabua** [comment]
a) is probably simpler at this stage and with less impact overall. We currently default to 3.6.0 but taking that stuff might impact old version usage negatively.

Using the exec approach sounds interesting but I wont have time to look at it at all or test it on the various systems either. So unless you or someone else provides a PR this will have to stay open for a while.

**Comment by gzm55** [comment]
> a) is probably simpler at this stage and with less impact overall. We currently default to 3.6.0 but taking that stuff might impact old version usage negatively.

If we can detect the version of maven, we may be select different action and try to not impact old version.

> 
> Using the exec approach sounds interesting but I wont have time to look at it at all or test it on the various systems either. So unless you or someone else provides a PR this will have to stay open for a while.

OK. b) Since java has no `execv()` api to replace current process, we need to mimic the `PathAssembler` in a portable script way or before `exec` mvn, run another java process for `PathAssembler` which may slow down the boot progress a little.

**Comment by aaoferreira** [comment]
I'm having the same issue with maven 3.6.2, any workarounds available? I'd look into option b) if I had some spare time, but don't see it happening at least until next year

**Comment by aaoferreira** [comment]
While there's no permanent solution, I did a fix/hack in my repo that calls mvn directly.

The caveat is that I had to bump the java version to at least 1.7, due to the `ProcessBuilder` API only being available at this version and being significantly better for handling processes (specially the IO redirection) and I don't have much time to implement a java 1.5 friendly solution.

Here's the link in case someone is interested https://github.com/aaoferreira/maven-wrapper/commit/a51a20e7cfcd94a8a9b3e2aff14c88722539f304

**Comment by gzm55** [comment]
How about letting `MavenWrapperMain::main()` print the full path of `mvn` script after installing maven distribution. Then exec into `mvn` script in the wrapper script.

**Comment by gzm55** [comment]
@mosabua some time to review #157 ?

**Comment by mosabua** [comment]
No ... I am working with the Maven team to get the code into upstream. You will probably have to resubmit later ..

**Comment by gzm55** [comment]
will the wrapper be merged into maven?

**Comment by mosabua** [comment]
Thats the idea

**Comment by gzm55** [comment]
good news~
Then if the idea works, this pr will have to be resubmitted to Maven project?

**Comment by mosabua** [comment]
Wellll ... give us a week or two until we can announce details and plans..

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
