### ISSUE TITLE
No newline at end of properties file and unnecessary executable permissions

### ISSUE THREAD

**Issue by ptamarit** [takari/maven-wrapper#78]
On Linux, when running the following command:

```
mvn -N io.takari:maven:wrapper
```

- The file `.mvn/wrapper/maven-wrapper.properties` does not end with a new line.
- The following files have executable permission while it's not needed:
  - `mvnw.cmd`
  - `.mvn/wrapper/MavenWrapperDownloader.java`
  - `.mvn/wrapper/maven-wrapper.jar`
  - `.mvn/wrapper/maven-wrapper.properties`

**Comment by mosabua** [comment]
Released maven-wrapper 0.5.0 and takari-maven-plugin 0.7.0 .. does this still apply?

**Comment by ptamarit** [comment]
Hi,

I'm using takari-maven-plugin 0.7.4 and maven-wrapper 0.5.3.

Running the command:

```
$ mvn -N io.takari:maven:wrapper
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven:0.7.4:wrapper (default-cli) @ standalone-pom ---
[INFO] 
[INFO] Maven Wrapper version 0.5.3 has been successfully set up for your project.
[INFO] Using Apache Maven: 3.6.0
[INFO] Repo URL in properties file: https://repo.maven.apache.org/maven2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.655 s
[INFO] Finished at: 2019-03-20T15:26:36+01:00
[INFO] ------------------------------------------------------------------------
```
* The file `.mvn/wrapper/maven-wrapper.properties` now ends with a new line, *so this problem has been fixed*.
* The following files are still executable even though it's not needed, *so this problem is not fixed*:
    * `mvnw.cmd`
    * `.mvn/wrapper/MavenWrapperDownloader.java`
    * `.mvn/wrapper/maven-wrapper.jar`
    * `.mvn/wrapper/maven-wrapper.properties`

Cheers,
Pablo

**Comment by mosabua** [comment]
mvnw.cmd should be executable from all I understand (at least on Windows ...). The others I can look into.

**Comment by ptamarit** [comment]
Hi,

Windows does not have the concept of executable flags. Any regular file with the `exe` or `cmd` extension can be executed.

Cheers,
Pablo

**Comment by mosabua** [comment]
Thanks for that info. I will update my local setup and the git index and see if that works out.

**Comment by mosabua** [comment]
The permissions might have to do with my local workspace usage on a VM with a shared folder on the host. I rejigged my setup now and will test this setup with the next release.

**Comment by mosabua** [comment]
Tested locally with project checkout on native unix fs and all works as desired. Updated dev docs and will release new version shortly.
