### ISSUE TITLE
How about add document of available environment variable?

### ISSUE THREAD

**Issue by yokotaso** [takari/maven-wrapper#82]
In mvnw or mvnw.cmd, we can use a some environment variable:

- `JAVA_OPTS`
- `MAVEN_OPTS`

In my environment, I struggle with http proxy settings.
I have proxy settings  in maven settings file e.g. `.m2/settings.xml`  and
environemnt variable `http_proxy` `https_proxy` .

But mvnw won't work well. What I needed:

```
MAVEN_OPTS=-Dhttp.proxyHost=proxyHost \
-Dhttp.proxyPort=8000 \
-Dhttps.proxyHost=proxyHost \
-Dhttps.proxyPort=8000
```
So, It is good that there are document about using available envrionement variable and 
about using mvnw in http proxy envrionment.

May I send PR?

**Comment by mosabua** [comment]
This is general Java/Maven support and has nothing to do with the wrapper. We do not want to duplicate documentation of these projects within ours.
