### ISSUE TITLE
Remove TODO from `mvnw` script

### ISSUE THREAD

**Issue by mvitz** [takari/maven-wrapper#84]
It's common to search for comments with TODO in projects. This is done using `grep`, `ack`, `rg` or the TODO search feature of an IDE.

Unfortunately the `mvnw` script contains a TODO comment which is found in every project I work in. It would be nice if this comment could be removed or resolved.

**Comment by mosabua** [comment]
done

**Comment by mosabua** [comment]
will go out with next release
