### ISSUE TITLE
Consider using java.home from java output

### ISSUE THREAD

**Issue by dmitry-timofeev** [takari/maven-wrapper#90]
Unfortunately, `which java` does not work correctly for some users. For example, for [`jenv`](http://www.jenv.be/) users mvnw won't be able to determine the `JAVA_HOME` correctly and will print a warning each time it is invoked.

For the purpose of determining JAVA_HOME we use the following script in our projects:
```sh
"${JAVA_HOME:-$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk '{print $3}')}"
```

It works for system installations and for various tools that manage several Java installations.

**Comment by mosabua** [comment]
This assume grep and awk installed and only works on Linux. We can not use this as such.
