### ISSUE TITLE
Allow configurable download URL for better support of enterprise environment

### ISSUE THREAD

**Issue by adrianshum** [takari/maven-wrapper#95]
(Copied from my comment in  #16 )

Just tried Maven Wrapper + Takari Maven Plugin in environment with restricted internet access.  The limitation of requiring direction connection to `repo1.maven.org` is quite painful.

Instead of making the wrapper aware of `settings.xml` (as suggested #16), I have an alternative idea:

Similar to `distributionUrl`, can we provide ability to define base url for download?

Now we have 3 things that will be downloaded by the wrapper:

1. Maven Wrapper script downloading Maven dist.  It can now be overridden by `distributionUrl`, which is stored in `.mvn/wrapper/maven-wrapper.properties`
3. Maven Wrapper script downloading the wrapper jar if missing.  It is now hardcoded in the wrapper scripts, and `MavenWrapperDownloader.java` to download from `repo1.maven.org`
2. Takari Maven Plugin downloading the Maven Wrapper tarball.  It is now hardcoded to download from `repo1.maven.org`, and hardcoded to download to `$HOME/.m2/repository` (personally I would rather just download to tmp dir or `$HOME/.m2/wrapper/`, as not everyone store the local repo in home, e.g. in build server)

Given in most enterprise environments, there is a centralized repository manager + repository proxy.  If we can configure the above 3 download to download from that centralized repository manager, it will be good enough.

So could we allow the plugin (and the maven-wrapper.properties) to define

1. `wrapperDownloadBaseUrl`  (which is something like  `http://my.internal/repo` , default = `http://repo1.maven.org/maven2` )
2. `distributionUrl` : URL for Wrapper script to download Maven Dist.  Work just like now.  However, if it is not defined, we can derive from `$wrapperDownloadBaseUrl`
3. `wrapperJarDownloadUrl` : URL for Wrapper script to download the wrapper JAR if it is not available.  .If not defined, derive from `$wrapperDownloadBaseUrl` 
4. `wrapperDownloadUrl` : URL for Takari Maven Plugin to download the wrapper tarball.  If not defined, derive from `$wrapperDownloadBaseUrl`

With all these, the plugin could work like:

    mvn -N io.takari:maven:wrapper -DwrapperDownloadBaseUrl=http://my.internal/repo

(all 3 downloads will go to `http://my.internal/repo`)

    mvn -N io.takari:maven:wrapper -DwrapperDownloadBaseUrl=http://my.internal/repo -DdistributionUrl=http://another.repo/maven.zip

(wrapper tarball and jar downloads will go through `http://my.internal/repo`, while maven distribution zip will be downloaded from another `http://another.repo`)

I am pleased to implement this if it is agreed to be a acceptable approach.

(Should I create a separate issue in Takari plugin Github repo?)

**Comment by reinsch82** [comment]
I'm currently trying my luck with this.
your suggestion seems useful.
I'm not a maintainer of the projects though. But this is of value for my employer too.
See here: https://github.com/takari/takari-maven-plugin/pull/15
you might be also interested in this https://github.com/takari/maven-wrapper/pull/96

**Comment by mosabua** [comment]
Released maven-wrapper 0.5.0 and takari-maven-plugin 0.7.0
